#!/usr/bin/env bash
# Generates seed_demo.sql for App Review demo accounts.
# Requires: macOS `say` + `afconvert` (or any tool producing valid m4a/AAC clips).
#
# Output: backend/sql/seed_demo.sql
# Apply with:  wrangler d1 execute tones --remote --file=backend/sql/seed_demo.sql
#
# Re-running is safe: existing demo rows are deleted before re-inserting.

set -euo pipefail

OUT_DIR="$(cd "$(dirname "$0")" && pwd)"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

generate_clip() {
  local text="$1" outfile="$2"
  say -v Samantha -o "$TMP_DIR/clip.aiff" "$text"
  afconvert -f m4af -d aac -b 24000 "$TMP_DIR/clip.aiff" "$outfile" >/dev/null 2>&1
}

b64() { base64 -i "$1" | tr -d '\n'; }

generate_clip "hey, welcome to tones"          "$TMP_DIR/m1.m4a"
generate_clip "this is a voice message"        "$TMP_DIR/m2.m4a"
generate_clip "good morning, hope you're well" "$TMP_DIR/m3.m4a"
generate_clip "thanks for trying it out"       "$TMP_DIR/m4.m4a"
generate_clip "let's catch up later"           "$TMP_DIR/m5.m4a"

M1=$(b64 "$TMP_DIR/m1.m4a")
M2=$(b64 "$TMP_DIR/m2.m4a")
M3=$(b64 "$TMP_DIR/m3.m4a")
M4=$(b64 "$TMP_DIR/m4.m4a")
M5=$(b64 "$TMP_DIR/m5.m4a")

NOW=$(date +%s000)

# Stable IDs so re-runs replace cleanly.
U_REVIEW="00000000-0000-0000-0000-000000000001"
U_ALEX="00000000-0000-0000-0000-000000000002"
U_SAM="00000000-0000-0000-0000-000000000003"
U_JORDAN="00000000-0000-0000-0000-000000000004"
U_RILEY="00000000-0000-0000-0000-000000000005"
DM_ALEX="10000000-0000-0000-0000-000000000001"
DM_SAM="10000000-0000-0000-0000-000000000002"
GROUP="10000000-0000-0000-0000-000000000003"

cat > "$OUT_DIR/seed_demo.sql" <<SQL
-- Tones demo data for App Store reviewers.
-- Generated by seed_demo.sh — do not edit by hand.
-- Apple Guideline 2.1(a): pre-populated content for App Review.

DELETE FROM message_reads WHERE user_id IN ('$U_REVIEW','$U_ALEX','$U_SAM','$U_JORDAN','$U_RILEY');
DELETE FROM messages      WHERE chat_id IN ('$DM_ALEX','$DM_SAM','$GROUP');
DELETE FROM chat_members  WHERE chat_id IN ('$DM_ALEX','$DM_SAM','$GROUP');
DELETE FROM chats         WHERE id      IN ('$DM_ALEX','$DM_SAM','$GROUP');
DELETE FROM friends       WHERE user_id IN ('$U_REVIEW','$U_ALEX','$U_SAM','$U_JORDAN','$U_RILEY')
                             OR friend_id IN ('$U_REVIEW','$U_ALEX','$U_SAM','$U_JORDAN','$U_RILEY');
DELETE FROM blocks        WHERE user_id IN ('$U_REVIEW','$U_ALEX','$U_SAM','$U_JORDAN','$U_RILEY');
DELETE FROM sessions      WHERE user_id IN ('$U_REVIEW','$U_ALEX','$U_SAM','$U_JORDAN','$U_RILEY');
DELETE FROM users         WHERE id      IN ('$U_REVIEW','$U_ALEX','$U_SAM','$U_JORDAN','$U_RILEY');

INSERT INTO users (id, apple_sub, username, avatar_url, created_at, updated_at) VALUES
  ('$U_REVIEW', NULL, 'appreview', NULL, $NOW, $NOW),
  ('$U_ALEX',   NULL, 'alex',      NULL, $NOW, $NOW),
  ('$U_SAM',    NULL, 'sam',       NULL, $NOW, $NOW),
  ('$U_JORDAN', NULL, 'jordan',    NULL, $NOW, $NOW),
  ('$U_RILEY',  NULL, 'riley',     NULL, $NOW, $NOW);

INSERT INTO friends (id, user_id, friend_id, created_at) VALUES
  ('f0000001-0000-0000-0000-000000000001', '$U_REVIEW', '$U_ALEX',   $NOW),
  ('f0000001-0000-0000-0000-000000000002', '$U_ALEX',   '$U_REVIEW', $NOW),
  ('f0000001-0000-0000-0000-000000000003', '$U_REVIEW', '$U_SAM',    $NOW),
  ('f0000001-0000-0000-0000-000000000004', '$U_SAM',    '$U_REVIEW', $NOW),
  ('f0000001-0000-0000-0000-000000000005', '$U_REVIEW', '$U_JORDAN', $NOW),
  ('f0000001-0000-0000-0000-000000000006', '$U_JORDAN', '$U_REVIEW', $NOW),
  ('f0000001-0000-0000-0000-000000000007', '$U_REVIEW', '$U_RILEY',  $NOW),
  ('f0000001-0000-0000-0000-000000000008', '$U_RILEY',  '$U_REVIEW', $NOW);

INSERT INTO chats (id, type, title, avatar_url, created_at, updated_at) VALUES
  ('$DM_ALEX', 'dm',    NULL,        NULL, $NOW, $NOW),
  ('$DM_SAM',  'dm',    NULL,        NULL, $NOW, $NOW),
  ('$GROUP',   'group', 'weekend crew', NULL, $NOW, $NOW);

INSERT INTO chat_members (chat_id, user_id) VALUES
  ('$DM_ALEX', '$U_REVIEW'),
  ('$DM_ALEX', '$U_ALEX'),
  ('$DM_SAM',  '$U_REVIEW'),
  ('$DM_SAM',  '$U_SAM'),
  ('$GROUP',   '$U_REVIEW'),
  ('$GROUP',   '$U_JORDAN'),
  ('$GROUP',   '$U_RILEY'),
  ('$GROUP',   '$U_ALEX');

INSERT INTO messages (id, chat_id, sender_id, audio_base64, duration_ms, created_at) VALUES
  ('m0000001-0000-0000-0000-000000000001', '$DM_ALEX', '$U_ALEX',   '$M1', 1500, $NOW - 600000),
  ('m0000001-0000-0000-0000-000000000002', '$DM_ALEX', '$U_REVIEW', '$M2', 1800, $NOW - 540000),
  ('m0000001-0000-0000-0000-000000000003', '$DM_ALEX', '$U_ALEX',   '$M5', 1700, $NOW - 480000),
  ('m0000001-0000-0000-0000-000000000004', '$DM_SAM',  '$U_SAM',    '$M3', 2200, $NOW - 360000),
  ('m0000001-0000-0000-0000-000000000005', '$GROUP',   '$U_JORDAN', '$M1', 1500, $NOW - 240000),
  ('m0000001-0000-0000-0000-000000000006', '$GROUP',   '$U_RILEY',  '$M4', 2000, $NOW - 180000),
  ('m0000001-0000-0000-0000-000000000007', '$GROUP',   '$U_ALEX',   '$M5', 1700, $NOW -  60000);
SQL

echo "Wrote $OUT_DIR/seed_demo.sql ($(wc -c < "$OUT_DIR/seed_demo.sql") bytes)"
